version: "3"
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    hostname: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=Passw0rd
    volumes:
      - ./mysql/mysql:/var/lib/mysql
    networks:
      mynet:
        ipv4_address: 172.16.0.100
 
networks:
  mynet:
    ipam:
      config:
        - subnet: 172.16.0.0/24